### ISSUE TITLE
Recomendaciones para la pagina web 

### ISSUE THREAD

**Issue by juanjo0611** [Anfelesan/ISYC-Curriculum-UNAL#18]
Hola, espero que tengas un buen día, te escribo para recomendarte unos arreglos para la distribución de la pagina web que estas haciendo, primero en la parte del header,  la distribución de la información se ve muy sobre cargada, podrías simplificarlo un poco y si no se puede por diferentes requerimientos que te pidieron, podrías disminuir el tamaño de la información que no es muy relevante y así poder jugar un poco con la distribución de la información, aparte de esto, el tamaño de los recuadros de las materias, es muy desigual, podrías diseñar un estándar o un intervalo para el tamaño de los cuadros, ya sea resumiendo nombres e información con algunas abreviaciones, o reduciendo el numero de columnas mostradas a la vez para tener mas espacio, espero que alguno de estas recomendaciones te sirva y que tengas un buen dia.

**Comment by Anfelesan** [comment]
Hi!, I already was thinking about the matter cards sizes, but very thanks for recommendations about the header
